AWSTemplateFormatVersion: 2010-09-09
Resources:
  capstonecloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: ""
        Origins:
          - Id: capstone-loadbalancer-252989174.us-east-2.elb.amazonaws.com
            DomainName: capstone-loadbalancer-252989174.us-east-2.elb.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          TargetOriginId: capstone-loadbalancer-252989174.us-east-2.elb.amazonaws.com
          ViewerProtocolPolicy: "allow-all"
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
