AWSTemplateFormatVersion: 2010-09-09
Resources:
  cloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: ""
        Origins:
          - Id: ANDREW
            DomainName: ANDREW
            CustomOriginConfig:
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          TargetOriginId: ANDREW
          ViewerProtocolPolicy: "allow-all"
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
