apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capstone
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: capstone-1275240471.us-east-2.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capstone
                port:
                  number: 80